/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.70
 * Generated at: 2023-04-07 13:44:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.fix;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.DriverManager;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.PreparedStatement;

public final class dramaPoster_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.sql.SQLException");
    _jspx_imports_classes.add("java.sql.Connection");
    _jspx_imports_classes.add("java.sql.ResultSet");
    _jspx_imports_classes.add("java.sql.PreparedStatement");
    _jspx_imports_classes.add("java.sql.DriverManager");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");


	Connection conn = null;
	ResultSet rs= null;
	
	try {
		String dbURL = "jdbc:mysql://localhost:3306/AFO_schema";
		String dbID = "root";
		String dbPassword = "12345678";
		Class.forName("com.mysql.jdbc.Driver");
		conn = DriverManager.getConnection(dbURL, dbID, dbPassword);
	} catch(Exception e) {
		e.printStackTrace();
	}
	
	String SQL = "select * from coupangdrama ORDER BY id";
	
	PreparedStatement pstmt = conn.prepareStatement(SQL);
	rs = pstmt.executeQuery();
	
	
	

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("\n");
      out.write("<title>dramaPoster.jsp</title>\n");
      out.write("\n");
      out.write("<!-- 영화 포스터 크기 조절 css -->\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"fix/MovieCSS.css\">\n");
      out.write("\n");
      out.write("<!-- 텍스트 데코레이션 css -->\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"fix/text_decoration.css\">\n");
      out.write("\n");
      out.write("<!-- 슬릭 css -->\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"https://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css\"/>\n");
      out.write("\n");
      out.write("<!-- 슬릭 제이쿼리 -->\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.6.1/jquery.min.js\"></script>\n");
      out.write("\n");
      out.write("<!-- 슬릭 js -->\n");
      out.write("<script type=\"text/javascript\" src=\"https://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js\"></script>\n");
      out.write("\n");
      out.write("<!-- 폰트 어썸 cdn -->\n");
      out.write("<script src=\"https://kit.fontawesome.com/f727c89db8.js\" crossorigin=\"anonymous\"></script>\n");
      out.write("\n");
      out.write("\n");
      out.write("<script> \n");
      out.write("	$(function()	{\n");
      out.write("		$('.mainSlide').slick({\n");
      out.write("			slidesToShow: 5,\n");
      out.write("			slidesToScroll: 5,\n");
      out.write("			arrows: true,\n");
      out.write("			prevArrow: \"<i class='white prev_arrow fa-solid fa-circle-chevron-left' ></i>\",\n");
      out.write("			  //prevArrow: \"<button type='button' class='slick-prev'>이전</button>\",\n");
      out.write("			nextArrow: \"<i class='white next_arrow fa-solid fa-circle-chevron-right' ></i>\",\n");
      out.write("			dots: false,\n");
      out.write("			\n");
      out.write("			\n");
      out.write("		});\n");
      out.write("	}); \n");
      out.write("</script>\n");
      out.write("\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("	\n");
      out.write("	<p> <h2> <b> 한국 TV 프로그램 순위 </b> </h2> </p>\n");
      out.write("	\n");
      out.write("	<div class=\"mainSlide model1\">\n");
      out.write("			<div><img src=\"\"> \n");
      out.write("			<b> 재벌집 막내아들 </b> <br>\n");
      out.write("			2022. 한국. 넷플릭스. 평균 3.9 \n");
      out.write("			</div>\n");
      out.write("			<div><img src=\"\">슈룹</div>\n");
      out.write("			<div><img src=\"\">치얼업</div>\n");
      out.write("			<div><img src=\"\">수리남</div>\n");
      out.write("			<div><img src=\"\">소방서 옆 경찰서</div>\n");
      out.write("			<div><img src=\"\">\n");
      out.write("				<b>이상한 변호사 우영우</b> <br>\n");
      out.write("				2022. 한국. 웨이브. 평균 4.0\n");
      out.write("			</div>\n");
      out.write("	</div> \n");
      out.write("	\n");
      out.write("	<br>\n");
      out.write("\n");
      out.write("	<p> <h2> <b> 쿠팡플레이 top 드라마 </b> </h2> </p>\n");
      out.write("	<div class=\"mainSlide model1\">\n");
      out.write("	");

		while(rs.next()) {
			
			
	
      out.write("\n");
      out.write("	\n");
      out.write("	<div>\n");
      out.write("		<a href= ");
      out.print( rs.getString("link") );
      out.write(" >\n");
      out.write("			<img src= ");
      out.print( rs.getString("thumb") );
      out.write(" >\n");
      out.write("		</a>\n");
      out.write("		<b> ");
      out.print( rs.getString("title"));
      out.write(" </b> ");
      out.print( rs.getString("year") );
      out.write(" \n");
      out.write("		");
      out.print( rs.getString("platform") );
      out.write(" <br>\n");
      out.write("		\n");
      out.write("	 </div>\n");
      out.write("	\n");
      out.write("	\n");
      out.write("	\n");
      out.write("	");

		}
	
      out.write("\n");
      out.write("	  \n");
      out.write("	<!-- out.println(\"</div>\"); -->\n");
      out.write("	</div>\n");
      out.write("	\n");
      out.write("\n");
      out.write("\n");
      out.write("	<br>\n");
      out.write("	<p> <h2> <b> 왓챠 top 드라마 </b> </h2>\n");
      out.write("	<div class=\"mainSlide model1\">\n");
      out.write("			<div><img src=\"https://w.namu.la/s/adb6e88ef6dafc5c0470e9371d24f4b89072d6f66d8089f4f6a3a896c80c7488762637567665a2ce3246de4f23a746b6a2c2563153be38ca2657c75402484f07c2057e140e20d2375452463336072f6a260f0500399ead778f0fc24996a40203f2017f9b3bf4b1a2e21159819c694331\"> \n");
      out.write("			<b> 재벌집 막내아들 </b> <br>\n");
      out.write("			2022. 한국. 넷플릭스. 평균 3.9 \n");
      out.write("			</div>\n");
      out.write("			<div><img src=\"https://newsimg.sedaily.com/2022/09/01/26AWKW8JQJ_1.jpg\">슈룹</div>\n");
      out.write("			<div><img src=\"https://w.namu.la/s/e4d2950baac276a00b60e9b528e3c7b653a1df57475539288217e33acfaf7a58ac677eb68482e83099968817eba63ef2616643ebef3106f7afd7d3d9d6a7cc5b0a3b091f38ea3a7820fec3bb2d9a4337a620dd2784f0dc998e42546f4ebc2871\">치얼업</div>\n");
      out.write("			<div><img src=\"https://w.namu.la/s/7b444ff2e9931b42ca10993a3d45525edfa61d24c0a1e4986bad407d4fb901ff677ada1ab24557709af4edd59e0511a656f8915bb6932c7ee5972526e8f5e1ee08a05e0a6fb55f856a818aaa8cf76d9019c5f4d9e3b9f5e313f8863f23e55dd8d3bd179715aba5e7d3a731b381365ed0\">수리남</div>\n");
      out.write("			<div><img src=\"https://w.namu.la/s/df6b120591a36f4914742ea12ec08e76d2da274f7dc0269107a0cc8589b48609b79a1db9bc28417a9d12477ac2dfc1d729632adcedea9a7afb88f6e9488fa0b27512051934cce245acd00149ae9e603bb15e28648b564518568d2546b8023934b656b5cdde21bb814a9bdd59d416759b\">소방서 옆 경찰서</div>\n");
      out.write("			<div><img src=\"https://upload.wikimedia.org/wikipedia/ko/d/d3/%EC%9D%B4%EC%83%81%ED%95%9C_%EB%B3%80%ED%98%B8%EC%82%AC_%EC%9A%B0%EC%98%81%EC%9A%B0.jpg\">이상한 변호사 우영우</div>\n");
      out.write("	</div>\n");
      out.write("	\n");
      out.write("	\n");
      out.write("	\n");
      out.write("	\n");
      out.write("	<br>\n");
      out.write("	<p> <h2> <b> 웨이브 top 드라마 </b> </h2>\n");
      out.write("	<div class=\"mainSlide model1\">\n");
      out.write("			<div><img src=\"https://w.namu.la/s/adb6e88ef6dafc5c0470e9371d24f4b89072d6f66d8089f4f6a3a896c80c7488762637567665a2ce3246de4f23a746b6a2c2563153be38ca2657c75402484f07c2057e140e20d2375452463336072f6a260f0500399ead778f0fc24996a40203f2017f9b3bf4b1a2e21159819c694331\"> \n");
      out.write("			<b> 재벌집 막내아들 </b> <br>\n");
      out.write("			2022. 한국. 넷플릭스. 평균 3.9 \n");
      out.write("			</div>\n");
      out.write("			<div><img src=\"https://newsimg.sedaily.com/2022/09/01/26AWKW8JQJ_1.jpg\">슈룹</div>\n");
      out.write("			<div><img src=\"https://w.namu.la/s/e4d2950baac276a00b60e9b528e3c7b653a1df57475539288217e33acfaf7a58ac677eb68482e83099968817eba63ef2616643ebef3106f7afd7d3d9d6a7cc5b0a3b091f38ea3a7820fec3bb2d9a4337a620dd2784f0dc998e42546f4ebc2871\">치얼업</div>\n");
      out.write("			<div><img src=\"https://w.namu.la/s/7b444ff2e9931b42ca10993a3d45525edfa61d24c0a1e4986bad407d4fb901ff677ada1ab24557709af4edd59e0511a656f8915bb6932c7ee5972526e8f5e1ee08a05e0a6fb55f856a818aaa8cf76d9019c5f4d9e3b9f5e313f8863f23e55dd8d3bd179715aba5e7d3a731b381365ed0\">수리남</div>\n");
      out.write("			<div><img src=\"https://w.namu.la/s/df6b120591a36f4914742ea12ec08e76d2da274f7dc0269107a0cc8589b48609b79a1db9bc28417a9d12477ac2dfc1d729632adcedea9a7afb88f6e9488fa0b27512051934cce245acd00149ae9e603bb15e28648b564518568d2546b8023934b656b5cdde21bb814a9bdd59d416759b\">소방서 옆 경찰서</div>\n");
      out.write("			<div><img src=\"https://upload.wikimedia.org/wikipedia/ko/d/d3/%EC%9D%B4%EC%83%81%ED%95%9C_%EB%B3%80%ED%98%B8%EC%82%AC_%EC%9A%B0%EC%98%81%EC%9A%B0.jpg\">이상한 변호사 우영우</div>\n");
      out.write("	</div>\n");
      out.write("	\n");
      out.write("	<br>\n");
      out.write("	<p> <h2> <b> 웨이브 top 드라마 </b> </h2>\n");
      out.write("	<div class=\"mainSlide model1\">\n");
      out.write("			<div><img src=\"https://w.namu.la/s/adb6e88ef6dafc5c0470e9371d24f4b89072d6f66d8089f4f6a3a896c80c7488762637567665a2ce3246de4f23a746b6a2c2563153be38ca2657c75402484f07c2057e140e20d2375452463336072f6a260f0500399ead778f0fc24996a40203f2017f9b3bf4b1a2e21159819c694331\"> \n");
      out.write("			<b> 재벌집 막내아들 </b> <br>\n");
      out.write("			2022. 한국. 넷플릭스. 평균 3.9 \n");
      out.write("			</div>\n");
      out.write("			<div><img src=\"https://newsimg.sedaily.com/2022/09/01/26AWKW8JQJ_1.jpg\">슈룹</div>\n");
      out.write("			<div><img src=\"https://w.namu.la/s/e4d2950baac276a00b60e9b528e3c7b653a1df57475539288217e33acfaf7a58ac677eb68482e83099968817eba63ef2616643ebef3106f7afd7d3d9d6a7cc5b0a3b091f38ea3a7820fec3bb2d9a4337a620dd2784f0dc998e42546f4ebc2871\">치얼업</div>\n");
      out.write("			<div><img src=\"https://w.namu.la/s/7b444ff2e9931b42ca10993a3d45525edfa61d24c0a1e4986bad407d4fb901ff677ada1ab24557709af4edd59e0511a656f8915bb6932c7ee5972526e8f5e1ee08a05e0a6fb55f856a818aaa8cf76d9019c5f4d9e3b9f5e313f8863f23e55dd8d3bd179715aba5e7d3a731b381365ed0\">수리남</div>\n");
      out.write("			<div><img src=\"https://w.namu.la/s/df6b120591a36f4914742ea12ec08e76d2da274f7dc0269107a0cc8589b48609b79a1db9bc28417a9d12477ac2dfc1d729632adcedea9a7afb88f6e9488fa0b27512051934cce245acd00149ae9e603bb15e28648b564518568d2546b8023934b656b5cdde21bb814a9bdd59d416759b\">소방서 옆 경찰서</div>\n");
      out.write("			<div><img src=\"https://upload.wikimedia.org/wikipedia/ko/d/d3/%EC%9D%B4%EC%83%81%ED%95%9C_%EB%B3%80%ED%98%B8%EC%82%AC_%EC%9A%B0%EC%98%81%EC%9A%B0.jpg\">이상한 변호사 우영우</div>\n");
      out.write("	</div>\n");
      out.write("	\n");
      out.write("	<br>\n");
      out.write("	<p> <h2> <b> 디즈니 플러스 top 드라마 </b> </h2>\n");
      out.write("	<div class=\"mainSlide model1\">\n");
      out.write("			<div><img src=\"https://w.namu.la/s/adb6e88ef6dafc5c0470e9371d24f4b89072d6f66d8089f4f6a3a896c80c7488762637567665a2ce3246de4f23a746b6a2c2563153be38ca2657c75402484f07c2057e140e20d2375452463336072f6a260f0500399ead778f0fc24996a40203f2017f9b3bf4b1a2e21159819c694331\"> \n");
      out.write("			<b> 재벌집 막내아들 </b> <br>\n");
      out.write("			2022. 한국. 넷플릭스. 평균 3.9 \n");
      out.write("			</div>\n");
      out.write("			<div><img src=\"https://newsimg.sedaily.com/2022/09/01/26AWKW8JQJ_1.jpg\">슈룹</div>\n");
      out.write("			<div><img src=\"https://w.namu.la/s/e4d2950baac276a00b60e9b528e3c7b653a1df57475539288217e33acfaf7a58ac677eb68482e83099968817eba63ef2616643ebef3106f7afd7d3d9d6a7cc5b0a3b091f38ea3a7820fec3bb2d9a4337a620dd2784f0dc998e42546f4ebc2871\">치얼업</div>\n");
      out.write("			<div><img src=\"https://w.namu.la/s/7b444ff2e9931b42ca10993a3d45525edfa61d24c0a1e4986bad407d4fb901ff677ada1ab24557709af4edd59e0511a656f8915bb6932c7ee5972526e8f5e1ee08a05e0a6fb55f856a818aaa8cf76d9019c5f4d9e3b9f5e313f8863f23e55dd8d3bd179715aba5e7d3a731b381365ed0\">수리남</div>\n");
      out.write("			<div><img src=\"https://w.namu.la/s/df6b120591a36f4914742ea12ec08e76d2da274f7dc0269107a0cc8589b48609b79a1db9bc28417a9d12477ac2dfc1d729632adcedea9a7afb88f6e9488fa0b27512051934cce245acd00149ae9e603bb15e28648b564518568d2546b8023934b656b5cdde21bb814a9bdd59d416759b\">소방서 옆 경찰서</div>\n");
      out.write("			<div><img src=\"https://upload.wikimedia.org/wikipedia/ko/d/d3/%EC%9D%B4%EC%83%81%ED%95%9C_%EB%B3%80%ED%98%B8%EC%82%AC_%EC%9A%B0%EC%98%81%EC%9A%B0.jpg\">이상한 변호사 우영우</div>\n");
      out.write("	</div>\n");
      out.write("	\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
