/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.70
 * Generated at: 2023-03-16 09:38:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class id_005ffind_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<HTML>\n");
      out.write("<HEAD>\n");
      out.write("<TITLE>ID_find</TITLE>\n");
      out.write("<META NAME=\"Generator\" CONTENT=\"EditPlus\">\n");
      out.write("<META NAME=\"Author\" CONTENT=\"\">\n");
      out.write("<META NAME=\"Keywords\" CONTENT=\"\">\n");
      out.write("<META NAME=\"Description\" CONTENT=\"\">\n");
      out.write("\n");
      out.write("<style>\n");
      out.write("tr {\n");
      out.write(" border: 0px solid none;\n");
      out.write("}\n");
      out.write("\n");
      out.write(" \n");
      out.write("\n");
      out.write("k:hover {\n");
      out.write(" text-decoration: none;\n");
      out.write(" color: #9354ED\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("\n");
      out.write("\n");
      out.write("<script>\n");
      out.write(" function gohome() {\n");
      out.write("  var frm = document.idfindscreen;\n");
      out.write("  frm.method = \"post\";\n");
      out.write("  frm.action = \"./home.jsp\"; //넘어간화면\n");
      out.write("  frm.submit(); //등록이 될수 있는 조건이면, 정보를 보내겠다.\n");
      out.write(" }\n");
      out.write("\n");
      out.write(" function gojoin() {\n");
      out.write("  var frm = document.idfindscreen;\n");
      out.write("  frm.method = \"post\";\n");
      out.write("  frm.action = \"./join.jsp\"; //넘어간화면\n");
      out.write("  frm.submit(); //등록이 될수 있는 조건이면, 정보를 보내겠다.\n");
      out.write(" }\n");
      out.write("\n");
      out.write(" function gologin() {\n");
      out.write("  var frm = document.idfindscreen;\n");
      out.write("  frm.method = \"post\";\n");
      out.write("  frm.action = \"./login.jsp\";\n");
      out.write("  frm.submit();\n");
      out.write(" }\n");
      out.write("\n");
      out.write(" function goidfind() {\n");
      out.write("  var frm = document.idfindscreen;\n");
      out.write("  frm.method = \"post\";\n");
      out.write("  frm.action = \"./id_find.jsp\";\n");
      out.write("  frm.submit();\n");
      out.write(" }\n");
      out.write("\n");
      out.write(" function gopwfind() {\n");
      out.write("  var frm = document.idfindscreen;\n");
      out.write("  frm.method = \"post\";\n");
      out.write("  frm.action = \"./pw_find.jsp\";\n");
      out.write("  frm.submit();\n");
      out.write(" }\n");
      out.write(" function logout() {\n");
      out.write("  var frm = document.idfindscreen;\n");
      out.write("  frm.method = \"post\";\n");
      out.write("  frm.action = \"./logoutCtl.jsp\";\n");
      out.write("  frm.submit();\n");
      out.write(" }\n");
      out.write(" function id_search1() { //이름,핸드폰으로 '찾기' 버튼\n");
      out.write("\n");
      out.write("  var frm = document.idfindscreen;\n");
      out.write("\n");
      out.write("  if (frm.name.value.length < 1) {\n");
      out.write("   alert(\"이름을 입력해주세요\");\n");
      out.write("   return;\n");
      out.write("  }\n");
      out.write("\n");
      out.write("  if (frm.phone1.value.length<2 || frm.phone1.value.length>4) {\n");
      out.write("   alert(\"핸드폰번호를 정확하게 입력해주세요\");\n");
      out.write("   return;\n");
      out.write("  }\n");
      out.write("  if (frm.phone2.value.length<2 || frm.phone2.value.length>4) {\n");
      out.write("   alert(\"핸드폰번호를 정확하게 입력해주세요\");\n");
      out.write("   return;\n");
      out.write("  }\n");
      out.write("\n");
      out.write("  frm.method = \"post\";\n");
      out.write("  frm.action = \"./id_searchCtl.jsp\"; //넘어간화면\n");
      out.write("  frm.submit();  }\n");
      out.write("\n");
      out.write("​\n");
      out.write("\n");
      out.write(" function id_search2() { //이름,이메일로 '찾기' 버튼\n");
      out.write("\n");
      out.write("  var frm = document.idfindscreen;\n");
      out.write("\n");
      out.write("  if (frm.name2.value.length < 1) {\n");
      out.write("   alert(\"이름을 입력해주세요\");\n");
      out.write("   return;\n");
      out.write("  }\n");
      out.write("  if (frm.email.value.length < 1 || frm.e_domain.value.length < 1) {\n");
      out.write("   alert(\"이메일을 입력해주세요\");\n");
      out.write("   return;\n");
      out.write("  }\n");
      out.write("\n");
      out.write("  frm.method = \"post\";\n");
      out.write("  frm.action = \"./id_searchCtl2.jsp\"; //넘어간화면\n");
      out.write("  frm.submit();  }\n");
      out.write("\n");
      out.write("​\n");
      out.write("\n");
      out.write(" //이메일 부분\n");
      out.write("\n");
      out.write(" function checkid() {\n");
      out.write("\n");
      out.write("  var frm = document.idfindscreen;\n");
      out.write("\n");
      out.write("  var regExp = '/^([/\\w/g\\.-]+)@([\\da-z\\.-]+)\\.([a-z\\.]{2,6})$/';\n");
      out.write("\n");
      out.write("  if (!regExp.test(frm.email.value)) {\n");
      out.write("\n");
      out.write("   alert('올바른 email을 입력해주세요.');\n");
      out.write("\n");
      out.write("   frm.email.focus();\n");
      out.write("\n");
      out.write("  }\n");
      out.write("\n");
      out.write(" }\n");
      out.write("\n");
      out.write(" function domainCheck() {\n");
      out.write("\n");
      out.write("  var frm = document.idfindscreen;\n");
      out.write("\n");
      out.write("  if (frm.domain.value == 0) {\n");
      out.write("   frm.e_domain.value = \"\";\n");
      out.write("   frm.e_domain.disabled = false;\n");
      out.write("\n");
      out.write("  } else {\n");
      out.write("   frm.e_domain.value = frm.domain.value;\n");
      out.write("   frm.e_domain.disabled = true;\n");
      out.write("\n");
      out.write("  }\n");
      out.write("\n");
      out.write(" }\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("\n");
      out.write("</HEAD>\n");
      out.write("\n");
      out.write("<BODY>\n");
      out.write(" <form name=\"idfindscreen\">\n");
      out.write(" \n");
      out.write(" <!-- 헤더 파일인듯. -->\n");
      out.write("   ");
      out.write("\n");
      out.write("  <font face=\"Yang Rounded\">\n");
      out.write("\n");
      out.write("\n");
      out.write("   <table width=\"1330px\" height=\"430px\" align=\"center\">\n");
      out.write("    <tr>\n");
      out.write("     <td>\n");
      out.write("      <table width=\"600px\" align=\"center\" border=\"0\"\n");
      out.write("       style=\"color: black; background-color: #F6F6F6; font-size: 20px;\">\n");
      out.write("       <tr>\n");
      out.write("        <td>\n");
      out.write("         <table width=\"750px\" align=\"center\" border=0;\n");
      out.write("          style=\"background-color: white; margin-top: 3%\">\n");
      out.write("          <tr>\n");
      out.write("           <td align=\"center\"><img src=\"../img/miki_icon.png\"\n");
      out.write("            height=\"30px\"></td>\n");
      out.write("           <td>아이디 찾기</td>\n");
      out.write("           <td><div id=\"sub-title\">| 회원정보에 등록한 정보로 인증.</td>\n");
      out.write("           <td width=\"300px\"></td>\n");
      out.write("          </tr>\n");
      out.write("         </table>\n");
      out.write("        </td>\n");
      out.write("       </tr>\n");
      out.write("\n");
      out.write("       <tr>\n");
      out.write("        <td>\n");
      out.write("         <table width=\"800px\" height=\"300px\" align=\"center\"\n");
      out.write("          style=\"border: dotted 5px none; margin-top: 4%\">\n");
      out.write("\n");
      out.write("          <tr>\n");
      out.write("           <td>\n");
      out.write("            <table width=\"300px\" height=\"30px\" border=\"0\"\n");
      out.write("             style=\"margin-top: 3%; color: black; font-size: 18px;\">\n");
      out.write("             <tr>\n");
      out.write("              <td>&nbsp;&nbsp; <img src=\"../img/check.png\"\n");
      out.write("               height=\"30px\">\n");
      out.write("              </td>\n");
      out.write("              <td>&nbsp;이름,핸드폰번호로 찾기</td>\n");
      out.write("             </tr>\n");
      out.write("            </table>\n");
      out.write("           </td>\n");
      out.write("          </tr>\n");
      out.write("\n");
      out.write("          <tr>\n");
      out.write("           <td>\n");
      out.write("            <table width=\"380px\" height=\"70px\" align=\"center\" border=\"0\"\n");
      out.write("             style=\"font-size: 16px;\">\n");
      out.write("             <tr>\n");
      out.write("              <td>이름</td>\n");
      out.write("              <td><input type=\"text\" name=\"name\"></td>\n");
      out.write("             </tr>\n");
      out.write("             <tr>\n");
      out.write("              <td>휴대폰</td>\n");
      out.write("              <td><select name=\"phone\">\n");
      out.write("                <option value=\"010\" selected=\"selected\">010</option>\n");
      out.write("                <option value=\"011\">011</option>\n");
      out.write("                <option value=\"016\">016</option>\n");
      out.write("                <option value=\"017\">017</option>\n");
      out.write("              </select> - <input type=\"text\" name=\"phone1\" style=\"width: 70px\">\n");
      out.write("               - <input type=\"text\" name=\"phone2\" style=\"width: 70px\"></td>\n");
      out.write("             </tr>\n");
      out.write("            </table>\n");
      out.write("           </td>\n");
      out.write("          </tr>\n");
      out.write("\n");
      out.write(" \n");
      out.write("\n");
      out.write("          <tr>\n");
      out.write("           <td>\n");
      out.write("            <table width=\"140px\" height=\"10px\" border=\"0\"\n");
      out.write("             style=\"margin-top: 2%;\" align=\"center\">\n");
      out.write("             <tr>\n");
      out.write("              <td><input type=\"button\" name=\"enter1\" value=\"  찾기  \"\n");
      out.write("               align=\"center\"\n");
      out.write("               style=\"cursor: pointer; background: white; color: black; border-color: black;\"\n");
      out.write("               onClick=\"id_search1()\"></td>\n");
      out.write("              <td><input type=\"button\" name=\"cancle1\"\n");
      out.write("               value=\"  취소  \" align=\"center\"\n");
      out.write("               style=\"cursor: pointer; background: white; color: black; border-color: black;\"\n");
      out.write("               onClick=\"cancle()\"></td>\n");
      out.write("             </tr>\n");
      out.write("            </table>\n");
      out.write("           </td>\n");
      out.write("          </tr>\n");
      out.write("\n");
      out.write("          <tr>\n");
      out.write("           <td>\n");
      out.write("            <table width=\"300px\" height=\"20px\" border=\"0\"\n");
      out.write("             style=\"margin-top: 3%; font-size: 18px;\">\n");
      out.write("             <br>\n");
      out.write("             <br>\n");
      out.write("             <tr>\n");
      out.write("              <td>&nbsp;&nbsp; <img src=\"../img/check.png\"\n");
      out.write("               height=\"30px\">\n");
      out.write("              </td>\n");
      out.write("              <td>&nbsp;이름,이메일로 찾기</td>\n");
      out.write("             </tr>\n");
      out.write("            </table>\n");
      out.write("           </td>\n");
      out.write("          </tr>\n");
      out.write("\n");
      out.write("          <td>\n");
      out.write("           <table width=\"380px\" height=\"70px\" align=\"center\" border=\"0\"\n");
      out.write("            style=\"font-size: 16px;\">\n");
      out.write("            <tr>\n");
      out.write("             <td>이름</td>\n");
      out.write("             <td><input type=\"text\" name=\"name2\"></td>\n");
      out.write("            </tr>\n");
      out.write("            <tr>\n");
      out.write("             <td style=\"text-align: center;\">e-mail&nbsp;</td>\n");
      out.write("             <td><input type=\"text\" name=\"email\"\n");
      out.write("              style=\"width: 80px\" onblur=\"checkid()\"> @ <input\n");
      out.write("              type=\"text\" name=\"e_domain\" style=\"width: 80px\"> <select\n");
      out.write("              name=\"domain\" onchange=\"domainCheck();\">\n");
      out.write("               <option value=\"0\" selected=\"selected\">직접입력</option>\n");
      out.write("               <option value=\"naver.com\">naver.com</option>\n");
      out.write("               <option value=\"hanmail.net\">hanmail.net</option>\n");
      out.write("               <option value=\"nate.com\">nate.com</option>\n");
      out.write("               <option value=\"yahoo.com\">yahoo.com</option>\n");
      out.write("             </select></td>\n");
      out.write("            </tr>\n");
      out.write("           </table>\n");
      out.write("          </td>\n");
      out.write("          </tr>\n");
      out.write("\n");
      out.write("          <tr>\n");
      out.write("           <td>\n");
      out.write("            <table width=\"140px\" height=\"10px\" border=\"0\"\n");
      out.write("             style=\"margin-top: 2%\" align=\"center\">\n");
      out.write("             <tr>\n");
      out.write("              <td><input type=\"button\" name=\"enter2\" value=\"  찾기  \"\n");
      out.write("               align=\"center\"\n");
      out.write("               style=\"cursor: pointer; background: white; color: black; border-color: black;\"\n");
      out.write("               onClick=\"id_search2()\"></td>\n");
      out.write("              <td><input type=\"button\" name=\"cancle2\"\n");
      out.write("               value=\"  취소  \" align=\"center\"\n");
      out.write("               style=\"cursor: pointer; background: white; color: black; border-color: black\"\n");
      out.write("               onClick=\"cancle()\"></td>\n");
      out.write("             </tr>\n");
      out.write("            </table>\n");
      out.write("            <br>\n");
      out.write("           </td>\n");
      out.write("          </tr>\n");
      out.write("         </table>\n");
      out.write("        </td>\n");
      out.write("       </tr>\n");
      out.write("      </table>\n");
      out.write("     </td>\n");
      out.write("    </tr>\n");
      out.write("   </table>\n");
      out.write("\n");
      out.write("\n");
      out.write("  </font>\n");
      out.write(" </form>\n");
      out.write("</BODY>\n");
      out.write("</HTML> ");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
