/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.70
 * Generated at: 2023-03-16 10:33:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.io.PrintWriter;
import user.UserDAO;
import user.User;

public final class userInfo_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.io.PrintWriter");
    _jspx_imports_classes.add("user.User");
    _jspx_imports_classes.add("user.UserDAO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<meta name =\"viewport\" content=\"width=device-width\", initial-scale=\"1\">\n");
      out.write("\n");
      out.write("<title>JSP 게시판 웹 사이트</title>\n");
      out.write("\n");
      out.write("<!-- CSS only -->\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi\" crossorigin=\"anonymous\">\n");
      out.write("\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("	");

	String userID=null;
	if(session.getAttribute("userID")!=null){
		userID=(String)session.getAttribute("userID");
	}
	User user = new UserDAO().getUser(userID);
	
	
      out.write("\n");
      out.write("	<!-- 네비게이션 바 -->\n");
      out.write("	<!-- <nav class=\"navbar navbar-inverse\">\n");
      out.write("		<div class =\"navbar-header\">\n");
      out.write("			<button type=\"button\" class=\"navbar-toggle collapsed\"\n");
      out.write("				data-toggle=\"collapse\" data-target=\"#bs-example-navbar-collapse-1\"\n");
      out.write("				aria-expanded=\"false\">\n");
      out.write("				<span class =\"icon-bar\"></span>\n");
      out.write("				<span class =\"icon-bar\"></span>\n");
      out.write("				<span class =\"icon-bar\"></span>\n");
      out.write("			</button>\n");
      out.write("			<a class=\"navbar-brand\" href=\"main.jsp\">공유 다이어리📕</a>\n");
      out.write("		</div>\n");
      out.write("		<div class=\"collapse navbar-collapse\" id=\"bs-example-navbar-collapse-1\">\n");
      out.write("			<ul class=\"nav navbar-nav\">\n");
      out.write("				<li><a href=\"main.jsp\">main</a></li>\n");
      out.write("				<li><a href=\"bbs.jsp\">diary</a></li>\n");
      out.write("			</ul>\n");
      out.write("			<ul class=\"nav navbar-nav navbar-right\">\n");
      out.write("				<li class=\"dropdown\">\n");
      out.write("					<a href=\"#\" class=\"dropdown-toggle\"\n");
      out.write("						data-toggle=\"dropdown\" role=\"button\" aria-haspopup=\"true\"\n");
      out.write("						aria-expanded=\"false\">접속하기<span class=\"caret\"></span></a>\n");
      out.write("					<ul class=\"dropdown-menu\">\n");
      out.write("						<li><a href=\"logoutAction.jsp\">로그아웃</a></li>\n");
      out.write("					</ul>\n");
      out.write("				</li>\n");
      out.write("			</ul>\n");
      out.write("		</div>\n");
      out.write("	</nav> \n");
      out.write("	-->\n");
      out.write("	");

		
	
      out.write("\n");
      out.write("	<div class=\"container\">\n");
      out.write("		<div class=\"col-lg-4\"></div>\n");
      out.write("		<div class=\"col-lg-4\">\n");
      out.write("			<div class=\"jumbotron\" style=\"padding-top: 20px;\">\n");
      out.write("				<form method=\"post\" action=\"userUpdateAction.jsp\">  <!-- 회원정보 수정하는 페이지 -->\n");
      out.write("					<h3 style=\"text-align:center;\">내 정보</h3>\n");
      out.write("					<div class = \"form-group\">\n");
      out.write("						<input type=\"text\" class=\"form-control\" value=");
      out.print(user.getUserID());
      out.write(" name=\"userID\" maxlength=\"20\">\n");
      out.write("					</div>\n");
      out.write("					<div class=\"form-group\">\n");
      out.write("						<input type=\"password\" class=\"form-control\" value=");
      out.print(user.getUserPassword());
      out.write(" name=\"userPassword\" maxlength=\"20\">\n");
      out.write("					</div>\n");
      out.write("					\n");
      out.write("					<div class=\"form-group\">\n");
      out.write("						<input type=\"text\" class=\"form-control\" value=");
      out.print(user.getUserName());
      out.write(" name=\"userName\" maxlength=\"20\">\n");
      out.write("					</div>\n");
      out.write("					\n");
      out.write("					<div class=\"form-group\" style=\"text-align:center;\">\n");
      out.write("						<div class=\"btn-group\" data-toggle=\"buttons\"> <!-- 성별 나누는 부분 -->\n");
      out.write("						");
 
							// 내가 이부분 드롭박스 클릭으로 변경해 놔서 레퍼런스랑 다름.
							if(user.getUserGender().equals("남자")) {
						
      out.write("\n");
      out.write("							<label class=\"btn btn-success active\"> \n");
      out.write("						");

							} 
							else {
						
      out.write("\n");
      out.write("							<label class=\"btn btn-success\">\n");
      out.write("						");

							}
						
      out.write("		\n");
      out.write("								<input type=\"radio\" name=\"userGender\" autocomplete=\"off\" value=\"남자\" checked>남자\n");
      out.write("							</label>\n");
      out.write("						");

							if(user.getUserGender().equals("여자")){
						
      out.write("\n");
      out.write("								<label class=\"btn btn-success active\">\n");
      out.write("						");

							} else{
						
      out.write("\n");
      out.write("								<label class=\"btn btn-success\">\n");
      out.write("						");

							}
						
      out.write("	\n");
      out.write("								<input type=\"radio\" name=\"userGender\" autocomplete=\"off\" value=\"여자\" checked>여자\n");
      out.write("							</label>\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("					\n");
      out.write("					<div class=\"form-group\">\n");
      out.write("						<input type=\"email\" class=\"form-control\" value=");
      out.print(user.getUserEmail());
      out.write(" name=\"userEmail\" maxlength=\"20\">\n");
      out.write("					</div>\n");
      out.write("					\n");
      out.write("					<input type=\"submit\" class=\"btn btn-success form-control\" value=\"수정하기\">\n");
      out.write("				</form>\n");
      out.write("				\n");
      out.write("					<br>\n");
      out.write("            <form method=\"post\" action=\"userDeleteAction.jsp\">  <!-- 유저 탈퇴 버튼 -->\n");
      out.write("            		<input type=\"submit\" class=\"btn btn-danger pull-right\" value=\"탈퇴하기\">\n");
      out.write("            </form>\n");
      out.write("\n");
      out.write("					</div></div>\n");
      out.write("</div></div>\n");
      out.write("	\n");
      out.write("<!-- JavaScript Bundle with Popper -->\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3\" crossorigin=\"anonymous\"></script>\n");
      out.write("	\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
