/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.70
 * Generated at: 2023-01-13 10:43:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class welcome_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/fix/moviePoster.jsp", Long.valueOf(1673530209000L));
    _jspx_dependants.put("/fix/header.jsp", Long.valueOf(1673518242000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\" >\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width\", initial-scale=\"1\">\n");
      out.write("<title>welcome page</title>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("	<!-- 공통 네비게이션 바  -->\n");
      out.write("	");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width\", initial-scale=\"1\">\n");
      out.write("<title>header.jsp</title>\n");
      out.write("\n");
      out.write("<!-- CSS only -->\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi\" crossorigin=\"anonymous\">\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("\n");
      out.write("	<!-- 네비게이션 바 -->\n");
      out.write("	<nav class=\"navbar navbar-expand-lg bg-light\">\n");
      out.write("  <div class=\"container-fluid\">\n");
      out.write("    <a class=\"navbar-brand\" href=\"welcome.jsp\"> <b> All for one </b> </a>\n");
      out.write("    \n");
      out.write("    <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarSupportedContent\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\n");
      out.write("      <span class=\"navbar-toggler-icon\"></span>\n");
      out.write("    </button>\n");
      out.write("    \n");
      out.write("    <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\n");
      out.write("      <ul class=\"navbar-nav me-auto mb-2 mb-lg-0\">\n");
      out.write("        \n");
      out.write("        <li class=\"nav-item\">\n");
      out.write("          <a class=\"nav-link active\" aria-current=\"page\" href=\"Movie.jsp\"> <b> Movie </b> </a>\n");
      out.write("        </li>\n");
      out.write("        \n");
      out.write("        <li class=\"nav-item\">\n");
      out.write("          <a class=\"nav-link active\" aria-current=\"page\" href=\"Drama.jsp\">\n");
      out.write("          <b> Drama </b> </a>\n");
      out.write("        </li>\n");
      out.write("        \n");
      out.write("        <li class=\"nav-item\">\n");
      out.write("          <a class=\"nav-link active\" aria-current=\"page\" href=\"Webtoon.jsp\">\n");
      out.write("          <b> Webtoon </b> </a>\n");
      out.write("        </li>\n");
      out.write("        \n");
      out.write("        \n");
      out.write("        \n");
      out.write("      </ul>\n");
      out.write("      <form class=\"d-flex\" role=\"search\">\n");
      out.write("        <input class=\"form-control me-2\" type=\"search\" placeholder=\"제목을 입력해보세요\" aria-label=\"Search\">\n");
      out.write("        <button class=\"btn btn-outline-success\" type=\"submit\">search</button>\n");
      out.write("      </form>\n");
      out.write("      \n");
      out.write("      \n");
      out.write("      	<button type=\"button\" class=\"btn btn-outline-dark\">로그인</button>    \n");
      out.write("      \n");
      out.write("      <!--  회원가입 버튼인데 type을 어떻게 해야할지 아직 모르겠음 -->\n");
      out.write("      <button type=\"submit\" class=\"btn btn-dark\">회원가입</button>\n");
      out.write("      \n");
      out.write("      \n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("</nav>\n");
      out.write("\n");
      out.write("	<!-- JavaScript Bundle with Popper -->\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3\" crossorigin=\"anonymous\"></script>\n");
      out.write("\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
      out.write("\n");
      out.write("	\n");
      out.write("	<!-- 영화 포스터 파일들 include -->\n");
      out.write("	");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>poster.jsp</title>\n");
      out.write("\n");
      out.write("<!-- 영화 포스터 크기 조절 css -->\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"fix/MovieCSS.css\">\n");
      out.write("\n");
      out.write("<!-- 슬릭 css -->\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"https://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css\"/>\n");
      out.write("\n");
      out.write("<!-- 슬릭 제이쿼리 -->\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.6.1/jquery.min.js\"></script>\n");
      out.write("\n");
      out.write("<!-- 슬릭 js -->\n");
      out.write("<script type=\"text/javascript\" src=\"https://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js\"></script>\n");
      out.write("\n");
      out.write("<!-- 폰트 어썸 cdn -->\n");
      out.write("<script src=\"https://kit.fontawesome.com/f727c89db8.js\" crossorigin=\"anonymous\"></script>\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("	$(function(){\n");
      out.write("		 $('.slider-for').slick({\n");
      out.write("			  slidesToShow: 1,\n");
      out.write("			  slidesToScroll: 1,\n");
      out.write("			  arrows: false,\n");
      out.write("			  fade: true,\n");
      out.write("			  asNavFor: '.slider-nav'\n");
      out.write("			});\n");
      out.write("			\n");
      out.write("	});\n");
      out.write("\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("	$(function(){\n");
      out.write("		$('.slider-nav').slick({\n");
      out.write("			  slidesToShow: 3,\n");
      out.write("			  slidesToScroll: 1,\n");
      out.write("			  asNavFor: '.slider-for',\n");
      out.write("			  dots: true,\n");
      out.write("			  centerMode: true,\n");
      out.write("			  focusOnSelect: true,\n");
      out.write("			  arrows: true, /* 화살표  */\n");
      out.write("				prevArrow: \"<i class='prev_arrow fa-solid fa-circle-arrow-left'></i>\",\n");
      out.write("				  //prevArrow: \"<button type='button' class='slick-prev'>이전</button>\",\n");
      out.write("				nextArrow: \"<i class='next_arrow fa-solid fa-circle-arrow-right'></i>\",\n");
      out.write("			  \n");
      out.write("			});	\n");
      out.write("	})\n");
      out.write("\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("\n");
      out.write("<script> \n");
      out.write("	$(function()	{\n");
      out.write("		$('.mainSlide').slick({\n");
      out.write("			slidesToShow: 5,\n");
      out.write("			slidesToScroll: 5,\n");
      out.write("			arrows: true,\n");
      out.write("			prevArrow: \"<i class='prev_arrow fa-solid fa-circle-chevron-left'></i>\",\n");
      out.write("			  //prevArrow: \"<button type='button' class='slick-prev'>이전</button>\",\n");
      out.write("			nextArrow: \"<i class='next_arrow fa-solid fa-circle-chevron-right'></i>\",\n");
      out.write("			dots: false,\n");
      out.write("			\n");
      out.write("			\n");
      out.write("		});\n");
      out.write("	}); \n");
      out.write("</script>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<script> \n");
      out.write("	$(function()	{\n");
      out.write("		$('.multiple-items').slick({\n");
      out.write("			  infinite: true,\n");
      out.write("			  slidesToShow: 3,\n");
      out.write("			  slidesToScroll: 3,\n");
      out.write("			  autoplay: true,\n");
      out.write("			  autoplaySpeed: 2000,\n");
      out.write("			  arrows: true,\n");
      out.write("			  prevArrow: \"<i class='prev_arrow fa-solid fa-circle-arrow-left'></i>\",\n");
      out.write("			  //prevArrow: \"<button type='button' class='slick-prev'>이전</button>\",\n");
      out.write("			  nextArrow: \"<i class='next_arrow fa-solid fa-circle-arrow-right'></i>\",\n");
      out.write("			  //nextArrow: \"<button type='button' class='slick-next'>다음</button>\"\n");
      out.write("			});\n");
      out.write("	}); \n");
      out.write("</script>\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("	$(function()	{\n");
      out.write("		$('.test').slick({\n");
      out.write("			  infinite: true,\n");
      out.write("			  slidesToShow: 3,\n");
      out.write("			  slidesToScroll: 3,\n");
      out.write("			  dots: true,\n");
      out.write("			  dotsClass: true,\n");
      out.write("			  \n");
      out.write("			  autoplay: true,\n");
      out.write("			  autoplaySpeed: 2000, \n");
      out.write("			  arrows: true,\n");
      out.write("			  prevArrow: \"<i class='prev_arrow fa-solid fa-circle-arrow-left'></i>\",\n");
      out.write("			  //prevArrow: \"<button type='button' class='slick-prev'>이전</button>\",\n");
      out.write("			  nextArrow: \"<i class='next_arrow fa-solid fa-circle-arrow-right'></i>\",\n");
      out.write("		});\n");
      out.write("	}); \n");
      out.write("</script>\n");
      out.write("\n");
      out.write("<script> \n");
      out.write("	$(function()	{\n");
      out.write("		$('.test2').slick({\n");
      out.write("			infinite: true , /* 맨끝이미지에서 끝나지 않고 다시 맨앞으로 이동 */\n");
      out.write("	        slidesToShow: 3, /* 화면에 보여질 이미지 갯수*/\n");
      out.write("	        slidesToScroll: 3,  /*  스크롤시 이동할 이미지 갯수 */\n");
      out.write("	        autoplay: true, /* 자동으로 다음이미지 보여주기 */\n");
      out.write("	        arrows: true, /* 화살표  */\n");
      out.write("			prevArrow: \"<i class='prev_arrow fa-solid fa-circle-arrow-left'></i>\",\n");
      out.write("			  //prevArrow: \"<button type='button' class='slick-prev'>이전</button>\",\n");
      out.write("			nextArrow: \"<i class='next_arrow fa-solid fa-circle-arrow-right'></i>\",\n");
      out.write("	        \n");
      out.write("	        dots:true, /*  아래점  */\n");
      out.write("	        \n");
      out.write("	        autoplaySpeed:10000,/* 다음이미지로 넘어갈 시간 */\n");
      out.write("	        speed:1000 , /* 다음이미지로 넘겨질때 걸리는 시간 */\n");
      out.write("	        pauseOnHover:true, /*  마우스 호버시 슬라이드 이동 멈춤 */\n");
      out.write("	       //vertical:true,/*  세로방향으로 슬라이드를 원하면 추가하기// 기본값 가로방향 슬라이드*/\n");
      out.write("	       responsive: [\n");
      out.write("	         { /* 반응형웹*/\n");
      out.write("	                 breakpoint: 960, /*  기준화면사이즈 */\n");
      out.write("	                 settings: {slidesToShow:2 } /*  사이즈에 적용될 설정 */\n");
      out.write("	          },\n");
      out.write("	          { /* 반응형웹*/\n");
      out.write("	                 breakpoint: 768, /*  기준화면사이즈 */\n");
      out.write("	                 settings: {slidesToShow:1 } /*  사이즈에 적용될 설정 */\n");
      out.write("	          }\n");
      out.write("	        ]\n");
      out.write("			});\n");
      out.write("	}); \n");
      out.write("</script>\n");
      out.write("\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("	<p> <h2> <b> 박스오피스 순위 </b> </h2> </p>\n");
      out.write("	\n");
      out.write("	<div class=\"mainSlide\">\n");
      out.write("			<div><img src=\"https://search.pstatic.net/common?type=f&size=206x290&quality=100&direct=true&src=https%3A%2F%2Fs.pstatic.net%2Fmovie.phinf%2F20221215_185%2F1671091761840XXpCR_JPEG%2Fmovie_image.jpg\"> <b> 1. 아바타 : 물의 길 </b> </div>\n");
      out.write("			<div><img src=\"https://search.pstatic.net/common?type=f&size=206x290&quality=100&direct=true&src=https%3A%2F%2Fs.pstatic.net%2Fmovie.phinf%2F20221216_283%2F1671153488789d3g4j_JPEG%2Fmovie_image.jpg\"> <b> 2. 더 퍼스트 슬램덩크 </b> </div>\n");
      out.write("			<div><img src=\"https://search.pstatic.net/common?type=f&size=206x290&quality=100&direct=true&src=https%3A%2F%2Fs.pstatic.net%2Fmovie.phinf%2F20221213_158%2F1670910727328mpqYu_JPEG%2Fmovie_image.jpg\"> <b> 3. 영웅 </b> </div>\n");
      out.write("			<div><img src=\"https://search.pstatic.net/common?type=f&size=206x290&quality=100&direct=true&src=https%3A%2F%2Fs.pstatic.net%2Fmovie.phinf%2F20221201_211%2F1669870554793PK1EK_JPEG%2Fmovie_image.jpg\"> <b> 4. 장화신은 고양이: 끝내주는 모험 </b> </div>\n");
      out.write("			<div><img src=\"https://search.pstatic.net/common?type=f&size=206x290&quality=100&direct=true&src=https%3A%2F%2Fs.pstatic.net%2Fmovie.phinf%2F20230104_215%2F1672799975321zXBOp_JPEG%2Fmovie_image.jpg\"> <b> 5. 스위치 </b> </div>\n");
      out.write("			<div><img src=\"https://search.pstatic.net/common?type=f&size=206x290&quality=100&direct=true&src=https%3A%2F%2Fs.pstatic.net%2Fmovie.phinf%2F20221104_258%2F1667527490266scSO3_JPEG%2Fmovie_image.jpg\"> <b> 6. 오늘 밤, 세계에서 이 사랑이 사라진다 해도 </b> </div>\n");
      out.write("			<div><img src=\"https://search.pstatic.net/common?type=f&size=206x290&quality=100&direct=true&src=https%3A%2F%2Fs.pstatic.net%2Fmovie.phinf%2F20221221_213%2F1671610586374HUJ35_JPEG%2Fmovie_image.jpg\"> <b> 7. 유령 </b> </div>\n");
      out.write("			<div><img src=\"https://search.pstatic.net/common?type=f&size=206x290&quality=100&direct=true&src=https%3A%2F%2Fs.pstatic.net%2Fmovie.phinf%2F20221123_65%2F1669168819647KdX9K_JPEG%2Fmovie_image.jpg\"> <b> 8. 올빼미 </b> </div>\n");
      out.write("			<div><img src=\"https://search.pstatic.net/common?type=f&size=206x290&quality=100&direct=true&src=https%3A%2F%2Fs.pstatic.net%2Fmovie.phinf%2F20230109_50%2F1673243320823szNQY_JPEG%2Fmovie_image.jpg\"> <b> 9. 프린스 챠밍 </b> </div>\n");
      out.write("			<div><img src=\"https://search.pstatic.net/common?type=f&size=206x290&quality=100&direct=true&src=https%3A%2F%2Fs.pstatic.net%2Fmovie.phinf%2F20221227_79%2F1672105992961sDeVc_JPEG%2Fmovie_image.jpg\"> <b> 10. 시간을 꿈꾸는 소녀 </b> </div>\n");
      out.write("	</div>\n");
      out.write("	<br><br>\n");
      out.write("\n");
      out.write("	<p> <h2> <b> 넷플릭스 해외 top 영화 </b> </h2> </p>\n");
      out.write("	<div class=\"mainSlide\">\n");
      out.write("			<div><img src=\"https://www.themoviedb.org/t/p/w220_and_h330_face/6MEYnNtvyctpshK0nIi6Kor9Av9.jpg\"> <b> 1. 트롤의 습격 </b> </div>\n");
      out.write("			<div><img src=\"https://www.themoviedb.org/t/p/w220_and_h330_face/lrgmo1qluO9c2qdBduiu412fRDS.jpg\"> <b> 2. 나이브스 아웃: 글래스 어니언 </b> </div>\n");
      out.write("			<div><img src=\"https://www.themoviedb.org/t/p/w220_and_h330_face/ga8R3OiOMMgSvZ4cOj8x7prUNYZ.jpg\"> <b> 3. 로알드 달의 뮤지컬 마틸다 </b> </div>\n");
      out.write("			<div><img src=\"https://www.themoviedb.org/t/p/w220_and_h330_face/8Q7Zxnxdn64nGrA1qklKNnFJ7QB.jpg\"> <b> 4. 빅4 </b> </div>\n");
      out.write("			<div><img src=\"https://www.themoviedb.org/t/p/w220_and_h330_face/5LG3gldi20hLxBHmWlJtt92Y73k.jpg\"> <b> 5. 마이 네임 이즈 벤데타 </b> </div>\n");
      out.write("			<div><img src=\"https://www.themoviedb.org/t/p/w220_and_h330_face/6bdUtxydFXLtgcxHMMvlkNnRZWg.jpg\"> <b> 6. 기예르모 델로토의 피노키오 </b> </div>\n");
      out.write("			<div><img src=\"https://www.themoviedb.org/t/p/w220_and_h330_face/e4nR9m6nY7HpaaeiEL1ixaYqReq.jpg\"> <b> 7. 레슨 플렌 </b> </div>\n");
      out.write("			<div><img src=\"https://www.themoviedb.org/t/p/w220_and_h330_face/iMmMxF6f2OonUrXrHKBLSYAhXly.jpg\"> <b> 8. 보스베이비: 크리스마스 보너스 </b> </div>\n");
      out.write("			<div><img src=\"https://www.themoviedb.org/t/p/w220_and_h330_face/GRbeIj59bZgDshwUETHLG6M6T7.jpg\"> <b> 9. 장화신은 고양이 </b> </div>\n");
      out.write("			<div><img src=\"https://www.themoviedb.org/t/p/w220_and_h330_face/voddFVdjUoAtfoZZp2RUmuZILDI.jpg\"> <b> 10. 스파이더맨: 노 웨이 홈 </b> </div>\n");
      out.write("	</div>\n");
      out.write("	<br><br>\n");
      out.write("	\n");
      out.write("	<p> <h2> <b> 넷플릭스 한국 top 영화 </b> </h2>\n");
      out.write("	<div class=\"mainSlide\">\n");
      out.write("			<div><img src=\"https://www.themoviedb.org/t/p/w220_and_h330_face/xM9Jt2sA6QcvLuHKM0RI3BMtFc5.jpg\"> <b> 1. 20세기 소녀 </b> </div>\n");
      out.write("			<div><img src=\"https://www.themoviedb.org/t/p/w220_and_h330_face/zukuy8slSFF1OpokjGtGwuMcAQV.jpg\"> <b> 2. 서울대작전 </b> </div>\n");
      out.write("			<div><img src=\"https://www.themoviedb.org/t/p/w220_and_h330_face/yGXMia1VNEovB7014ldTHwT1r50.jpg\"> <b> 3. 헤어질 결심 </b> </div>\n");
      out.write("			<div><img src=\"https://www.themoviedb.org/t/p/w220_and_h330_face/aGKln9LeFkP30MAiwFiuaMmNvzG.jpg\"> <b> 4. 카터 </b> </div>\n");
      out.write("			<div><img src=\"https://www.themoviedb.org/t/p/w220_and_h330_face/i011PWRJcIVe8d9DscLagjRFuXd.jpg\"> <b> 5. 외계+인 1부 </b> </div>\n");
      out.write("			<div><img src=\"https://www.themoviedb.org/t/p/w220_and_h330_face/5j2YVF7VouLG0Ze96SEsj4DnVQM.jpg\"> <b> 6. 신과함께-죄와 벌 </b> </div>\n");
      out.write("			<div><img src=\"https://www.themoviedb.org/t/p/w220_and_h330_face/2ETx0U2Q5gUHtPJZiQ3hakTqyaR.jpg\"> <b> 7. 신과함께-인과 연 </b> </div>\n");
      out.write("			<div><img src=\"https://www.themoviedb.org/t/p/w220_and_h330_face/jjHccoFjbqlfr4VGLVLT7yek0Xn.jpg\"> <b> 8. 기생충 </b> </div>\n");
      out.write("			<div><img src=\"https://www.themoviedb.org/t/p/w220_and_h330_face/nOYyuJ2mNo6RWsFsTwApEyG3F4J.jpg\"> <b> 9. 야차 </b> </div>\n");
      out.write("			<div><img src=\"https://www.themoviedb.org/t/p/w220_and_h330_face/nCrh5EQYiYXEIFNrfb4ISm7TOOo.jpg\"> <b> 10. 부산행 </b> </div>\n");
      out.write("	</div>\n");
      out.write("	<br><br>\n");
      out.write("	\n");
      out.write("	<p> <h2> <b> 왓챠 해외 top 영화 </b> </h2>\n");
      out.write("	<div class=\"mainSlide\">\n");
      out.write("			<div><img src=\"https://www.themoviedb.org/t/p/w220_and_h330_face/GRbeIj59bZgDshwUETHLG6M6T7.jpg\"> <b> 1. 장화신은 고양이 </b> </div>\n");
      out.write("			<div><img src=\"https://www.themoviedb.org/t/p/w220_and_h330_face/mxdVTei65ymzhJlalIEtR1qSgV2.jpg\"> <b> 2. 극장판 귀멸의 칼날: 무한열차편 </b> </div>\n");
      out.write("			<div><img src=\"https://www.themoviedb.org/t/p/w220_and_h330_face/nlvcNogJK9R9iIj0YINApQE36FF.jpg\"> <b> 3. 핵소 고지 </b> </div>\n");
      out.write("			<div><img src=\"https://www.themoviedb.org/t/p/w220_and_h330_face/zDNAeWU0PxKolEX1D8Vn1qWhGjH.jpg\"> <b> 4. 인터스텔라 </b> </div>\n");
      out.write("			<div><img src=\"https://www.themoviedb.org/t/p/w220_and_h330_face/xKH44zYwhviUnnkOy7ReZeEcIp3.jpg\"> <b> 5. 썸머 고스트 </b> </div>\n");
      out.write("			<div><img src=\"https://www.themoviedb.org/t/p/w220_and_h330_face/66Vx0C2cVL0mym0tfKgF4gmcuhA.jpg\"> <b> 6. 소드 아트 온라인 -프로그레시브- 별 없는 밤의 아리아 </b> </div>\n");
      out.write("			<div><img src=\"https://www.themoviedb.org/t/p/w220_and_h330_face/9DVdYFqGXdMPLgIfqQxNpUWz266.jpg\"> <b> 7. 탑 건 </b> </div>\n");
      out.write("			<div><img src=\"https://www.themoviedb.org/t/p/w220_and_h330_face/dYwwlFLd8WNrfa3s6HBzAbH3QXG.jpg\"> <b> 8. 퓨리 </b> </div>\n");
      out.write("			<div><img src=\"https://www.themoviedb.org/t/p/w220_and_h330_face/7brBiaaH1sToGV1YBi5EIUnyjo0.jpg\"> <b> 9. 나이브스 아웃 </b> </div>\n");
      out.write("			<div><img src=\"https://www.themoviedb.org/t/p/w220_and_h330_face/xdJxoq0dtkchOkUz5UVKuxn7a2V.jpg\"> <b> 10. 포레스트 검프 </b> </div>\n");
      out.write("	</div>\n");
      out.write("	<br><br>\n");
      out.write("	\n");
      out.write("	<p> <h2> <b> 왓챠 한국 top 영화 </b> </h2>\n");
      out.write("	<div class=\"mainSlide\">\n");
      out.write("			<div><img src=\"https://www.themoviedb.org/t/p/w220_and_h330_face/5j2YVF7VouLG0Ze96SEsj4DnVQM.jpg\"> <b> 1. 신과함께-죄와 벌 </b> </div>\n");
      out.write("			<div><img src=\"https://www.themoviedb.org/t/p/w220_and_h330_face/jjHccoFjbqlfr4VGLVLT7yek0Xn.jpg\"> <b> 2. 기생충 </b> </div>\n");
      out.write("			<div><img src=\"https://www.themoviedb.org/t/p/w220_and_h330_face/aPUxyX8mfxMEgOvbzPyNhNkdfN.jpg\"> <b> 3. 장화, 홍련 </b> </div>\n");
      out.write("			<div><img src=\"https://www.themoviedb.org/t/p/w220_and_h330_face/ydjxrQ040Br6MTIM7vULoNq0pWv.jpg\"> <b> 4. 연애 빠진 로맨스 </b> </div>\n");
      out.write("			<div><img src=\"https://www.themoviedb.org/t/p/w220_and_h330_face/2I18GAALWplcv60v7c3HmdzjMGW.jpg\"> <b> 5. 박쥐 </b> </div>\n");
      out.write("			<div><img src=\"https://www.themoviedb.org/t/p/w220_and_h330_face/eEQvJerAVak8hWzSYKbvImQIZfu.jpg\"> <b> 6. 방법: 재차의 </b> </div>\n");
      out.write("			<div><img src=\"https://www.themoviedb.org/t/p/w220_and_h330_face/7fQlPXebfjEqjysW3rv4RyNplih.jpg\"> <b> 7. 감기 </b> </div>\n");
      out.write("			<div><img src=\"https://www.themoviedb.org/t/p/w220_and_h330_face/1n5q3XpEhCe7TnGHzsHs5pwVT8O.jpg\"> <b> 8. 백두산 </b> </div>\n");
      out.write("			<div><img src=\"https://www.themoviedb.org/t/p/w220_and_h330_face/pRZMtKQpP3fH84YXs02yytUk4ee.jpg\"> <b> 9. 설국열차 </b> </div>\n");
      out.write("			<div><img src=\"https://www.themoviedb.org/t/p/w220_and_h330_face/sCLqWiJxp2rq2wuvuv8N2KvaNhB.jpg\"> <b> 10. 곤지암 </b> </div>\n");
      out.write("	</div>\n");
      out.write("	<br><br>\n");
      out.write("	\n");
      out.write("	<p> <h2> <b> 웨이브 top 영화 </b> </h2>\n");
      out.write("	<div class=\"mainSlide\">\n");
      out.write("			<div><img src=\"\"> <b> 1. 아바타 : 물의 길 </b> </div>\n");
      out.write("			<div><img src=\"\"> <b> 2. 더 퍼스트 슬램덩크 </b> </div>\n");
      out.write("			<div><img src=\"\"> <b> 3. 영웅 </b> </div>\n");
      out.write("			<div><img src=\"\"> <b> 4. 장화신은 고양이: 끝내주는 모험 </b> </div>\n");
      out.write("			<div><img src=\"\"> <b> 5. 스위치 </b> </div>\n");
      out.write("			<div><img src=\"\"> <b> 6. 오늘 밤, 세계에서 이 사랑이 사라진다 해도 </b> </div>\n");
      out.write("			<div><img src=\"\"> <b> 7. 유령 </b> </div>\n");
      out.write("			<div><img src=\"\"> <b> 8. 올빼미 </b> </div>\n");
      out.write("			<div><img src=\"\"> <b> 9. 프린스 챠밍 </b> </div>\n");
      out.write("			<div><img src=\"\"> <b> 10. 시간을 꿈꾸는 소녀 </b> </div>\n");
      out.write("	</div>\n");
      out.write("	\n");
      out.write("	<p> <h2> <b> 디즈니 플러스 top 영화 </b> </h2>\n");
      out.write("	<div class=\"mainSlide\">\n");
      out.write("			<div><img src=\"\"> <b> 1. 아바타 : 물의 길 </b> </div>\n");
      out.write("			<div><img src=\"\"> <b> 2. 더 퍼스트 슬램덩크 </b> </div>\n");
      out.write("			<div><img src=\"\"> <b> 3. 영웅 </b> </div>\n");
      out.write("			<div><img src=\"\"> <b> 4. 장화신은 고양이: 끝내주는 모험 </b> </div>\n");
      out.write("			<div><img src=\"\"> <b> 5. 스위치 </b> </div>\n");
      out.write("			<div><img src=\"\"> <b> 6. 오늘 밤, 세계에서 이 사랑이 사라진다 해도 </b> </div>\n");
      out.write("			<div><img src=\"\"> <b> 7. 유령 </b> </div>\n");
      out.write("			<div><img src=\"\"> <b> 8. 올빼미 </b> </div>\n");
      out.write("			<div><img src=\"\"> <b> 9. 프린스 챠밍 </b> </div>\n");
      out.write("			<div><img src=\"\"> <b> 10. 시간을 꿈꾸는 소녀 </b> </div>\n");
      out.write("	</div>\n");
      out.write("	\n");
      out.write("	<p> <h2> <b> #로맨스 top 10 </b> </h2>\n");
      out.write("	<div class=\"mainSlide\">\n");
      out.write("			<div><img src=\"\"> <b> 1. 아바타 : 물의 길 </b> </div>\n");
      out.write("			<div><img src=\"\"> <b> 2. 더 퍼스트 슬램덩크 </b> </div>\n");
      out.write("			<div><img src=\"\"> <b> 3. 영웅 </b> </div>\n");
      out.write("			<div><img src=\"\"> <b> 4. 장화신은 고양이: 끝내주는 모험 </b> </div>\n");
      out.write("			<div><img src=\"\"> <b> 5. 스위치 </b> </div>\n");
      out.write("			<div><img src=\"\"> <b> 6. 오늘 밤, 세계에서 이 사랑이 사라진다 해도 </b> </div>\n");
      out.write("			<div><img src=\"\"> <b> 7. 유령 </b> </div>\n");
      out.write("			<div><img src=\"\"> <b> 8. 올빼미 </b> </div>\n");
      out.write("			<div><img src=\"\"> <b> 9. 프린스 챠밍 </b> </div>\n");
      out.write("			<div><img src=\"\"> <b> 10. 시간을 꿈꾸는 소녀 </b> </div>\n");
      out.write("	</div>\n");
      out.write("	\n");
      out.write("	<p> <h2> <b> #판타지 top 10 </b> </h2>\n");
      out.write("	<div class=\"mainSlide\">\n");
      out.write("			<div><img src=\"\"> <b> 1. 아바타 : 물의 길 </b> </div>\n");
      out.write("			<div><img src=\"\"> <b> 2. 더 퍼스트 슬램덩크 </b> </div>\n");
      out.write("			<div><img src=\"\"> <b> 3. 영웅 </b> </div>\n");
      out.write("			<div><img src=\"\"> <b> 4. 장화신은 고양이: 끝내주는 모험 </b> </div>\n");
      out.write("			<div><img src=\"\"> <b> 5. 스위치 </b> </div>\n");
      out.write("			<div><img src=\"\"> <b> 6. 오늘 밤, 세계에서 이 사랑이 사라진다 해도 </b> </div>\n");
      out.write("			<div><img src=\"\"> <b> 7. 유령 </b> </div>\n");
      out.write("			<div><img src=\"\"> <b> 8. 올빼미 </b> </div>\n");
      out.write("			<div><img src=\"\"> <b> 9. 프린스 챠밍 </b> </div>\n");
      out.write("			<div><img src=\"\"> <b> 10. 시간을 꿈꾸는 소녀 </b> </div>\n");
      out.write("	</div>\n");
      out.write("	\n");
      out.write("	<p> <h2> <b> #코미디 top 10 </b> </h2>\n");
      out.write("	<div class=\"mainSlide\">\n");
      out.write("			<div><img src=\"\"> <b> 1. 아바타 : 물의 길 </b> </div>\n");
      out.write("			<div><img src=\"\"> <b> 2. 더 퍼스트 슬램덩크 </b> </div>\n");
      out.write("			<div><img src=\"\"> <b> 3. 영웅 </b> </div>\n");
      out.write("			<div><img src=\"\"> <b> 4. 장화신은 고양이: 끝내주는 모험 </b> </div>\n");
      out.write("			<div><img src=\"\"> <b> 5. 스위치 </b> </div>\n");
      out.write("			<div><img src=\"\"> <b> 6. 오늘 밤, 세계에서 이 사랑이 사라진다 해도 </b> </div>\n");
      out.write("			<div><img src=\"\"> <b> 7. 유령 </b> </div>\n");
      out.write("			<div><img src=\"\"> <b> 8. 올빼미 </b> </div>\n");
      out.write("			<div><img src=\"\"> <b> 9. 프린스 챠밍 </b> </div>\n");
      out.write("			<div><img src=\"\"> <b> 10. 시간을 꿈꾸는 소녀 </b> </div>\n");
      out.write("	</div>\n");
      out.write("	\n");
      out.write("	<p> <h2> <b> #스릴러 top 10 </b> </h2>\n");
      out.write("	<div class=\"mainSlide\">\n");
      out.write("			<div><img src=\"\"> <b> 1. 아바타 : 물의 길 </b> </div>\n");
      out.write("			<div><img src=\"\"> <b> 2. 더 퍼스트 슬램덩크 </b> </div>\n");
      out.write("			<div><img src=\"\"> <b> 3. 영웅 </b> </div>\n");
      out.write("			<div><img src=\"\"> <b> 4. 장화신은 고양이: 끝내주는 모험 </b> </div>\n");
      out.write("			<div><img src=\"\"> <b> 5. 스위치 </b> </div>\n");
      out.write("			<div><img src=\"\"> <b> 6. 오늘 밤, 세계에서 이 사랑이 사라진다 해도 </b> </div>\n");
      out.write("			<div><img src=\"\"> <b> 7. 유령 </b> </div>\n");
      out.write("			<div><img src=\"\"> <b> 8. 올빼미 </b> </div>\n");
      out.write("			<div><img src=\"\"> <b> 9. 프린스 챠밍 </b> </div>\n");
      out.write("			<div><img src=\"\"> <b> 10. 시간을 꿈꾸는 소녀 </b> </div>\n");
      out.write("	</div>\n");
      out.write("	\n");
      out.write("</body>\n");
      out.write("</html>");
      out.write("\n");
      out.write("	\n");
      out.write("\n");
      out.write("	\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
